### ISSUE TITLE
Successful installation but cannot run program

### ISSUE THREAD

**Issue by sgavril** [AlphaGenes/AlphaImpute2#1]
Hello,

I just read the pre-print for AlphaImpute2 and I am excited to test it out. After installing, I try to run AlphaImpute2 without any arguments and I am met with the following error below:

```
[stefan@stefan-81x2 AlphaImpute2]$ pip uninstall AlphaImpute2 -y
Found existing installation: AlphaImpute2 0.0.3
Uninstalling AlphaImpute2-0.0.3:
  Successfully uninstalled AlphaImpute2-0.0.3
[stefan@stefan-81x2 AlphaImpute2]$ pip install dist/AlphaImpute2-0.0.3-py3-none-any.whl 
Defaulting to user installation because normal site-packages is not writeable
Processing ./dist/AlphaImpute2-0.0.3-py3-none-any.whl
Requirement already satisfied: numba>=0.49.0 in /home/stefan/.local/lib/python3.8/site-packages (from AlphaImpute2==0.0.3) (0.52.0)
Requirement already satisfied: numpy>=1.19 in /home/stefan/.local/lib/python3.8/site-packages (from AlphaImpute2==0.0.3) (1.19.4)
Requirement already satisfied: llvmlite<0.36,>=0.35.0 in /home/stefan/.local/lib/python3.8/site-packages (from numba>=0.49.0->AlphaImpute2==0.0.3) (0.35.0)
Requirement already satisfied: setuptools in /usr/lib/python3.8/site-packages (from numba>=0.49.0->AlphaImpute2==0.0.3) (50.3.2)
Installing collected packages: AlphaImpute2
Successfully installed AlphaImpute2-0.0.3
[stefan@stefan-81x2 AlphaImpute2]$ AlphaImpute2
Traceback (most recent call last):
  File "/usr/bin/AlphaImpute2", line 5, in <module>
    from alphaimpute2.alphaimpute2 import main
  File "/home/stefan/.local/lib/python3.8/site-packages/alphaimpute2/alphaimpute2.py", line 4, in <module>
    from .Imputation import ParticlePhasing
  File "/home/stefan/.local/lib/python3.8/site-packages/alphaimpute2/Imputation/ParticlePhasing.py", line 19, in <module>
    from . import PhasingObjects
  File "/home/stefan/.local/lib/python3.8/site-packages/alphaimpute2/Imputation/PhasingObjects.py", line 17, in <module>
    from . import Imputation
  File "/home/stefan/.local/lib/python3.8/site-packages/alphaimpute2/Imputation/Imputation.py", line 2, in <module>
    from numba import jit, int8, int32, boolean, jitclass, float32, int64
ImportError: cannot import name 'jitclass' from 'numba' (/home/stefan/.local/lib/python3.8/site-packages/numba/__init__.py)

```

I'm not sure what is going wrong with the installation, and any suggestions would be greatly appreciated. If it is relevant, I am running Manjaro 20.2. Many thanks.

**Comment by janaobsteter** [comment]
@sgavril , it looks like there is an issue with the Numba installation or the pip isn't pointing to the python with Numba installed. Could you open python in the terminal and type `from numba import jit` and if this works `from numba import jitclass` and report the output? Yout might need to install / reinstall Numba.
Alternatively, if you have the conda (anaconda / miniconda) installed, I would suggest installing the AlphaImpute2 within the conda environment.

**Comment by sgavril** [comment]
Hello @janaobsteter, thanks for the quick reply. Below is the output from the first command:
```
Python 3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from numba import jit
>>> from numba import jitclass
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'jitclass' from 'numba' (/usr/lib/python3.8/site-packages/numba/__init__.py)
>>> 

```
I would prefer to use Conda if that is available, but I'm getting a packages not found error. Is there a link to anaconda cloud for alphaimpute2/suggested command?

**Comment by janaobsteter** [comment]
@sgavril, can you also report the versions of Numba and Numpy:
`import numba`
`print(numba.__version__)`
`import numpy`
`print(numpy.__version__)`

Maybe updating Numba would solve the problem (via `pip install numba`).

By using conda I meant locally, instead of pip. The Numba site also recommends to use it with Conda (the reason being Conda installs and updates all the packages). I you want you can download Conda (Anaconda or Miniconda - I tried with Anaconda3 and it worked perfectly: https://www.anaconda.com/products/individual). Works with Arch/Manjaro Linux. Then your python path should point to the Conda python which has no problem handling numba and AlphaImpute2 (at least in my case).

So maybe first try to run the `pip install numba` command and try running AlphaImpute2 again (or open python and try to import jitclass).If this doesn't work, then I would recommend installing conda - and I am happy to help you with that!

**Comment by sgavril** [comment]
@janaobsteter your suggestion to use Conda worked great! Thanks so much for your help.
