### ISSUE TITLE
Still getting error: `cannot import name 'jitclass' from 'numba'`

### ISSUE THREAD

**Issue by brettellebi** [AlphaGenes/AlphaImpute2#11]
Hi there,

Noting that you've already tried to address this issue, after installing the pip wheel inside a python 3.8 Singularity container on Linux, or a conda environment on MacOS, I still get the following error when trying to initiate the software:

```
username@hostname:~$ AlphaImpute2

Traceback (most recent call last):
  File "/usr/local/bin/AlphaImpute2", line 5, in <module>
    from alphaimpute2.alphaimpute2 import main
  File "/usr/local/lib/python3.8/site-packages/alphaimpute2/alphaimpute2.py", line 4, in <module>
    from .Imputation import ParticlePhasing
  File "/usr/local/lib/python3.8/site-packages/alphaimpute2/Imputation/ParticlePhasing.py", line 19, in <module>
    from . import PhasingObjects
  File "/usr/local/lib/python3.8/site-packages/alphaimpute2/Imputation/PhasingObjects.py", line 17, in <module>
    from . import Imputation
  File "/usr/local/lib/python3.8/site-packages/alphaimpute2/Imputation/Imputation.py", line 2, in <module>
    from numba import jit, int8, int32, boolean, jitclass, float32, int64
ImportError: cannot import name 'jitclass' from 'numba' (/usr/local/lib/python3.8/site-packages/numba/__init__.py)
```

Your assistance would be appreciated. 

Best,

Ian

**Comment by gregorgorjanc** [comment]
@brettellebi we haven't updated wheels, yet! Can you install from the source which does contain new way of loading numba?

**Comment by brettellebi** [comment]
Apologies for my ignorance Gregor, but how do I do that?

**Comment by gregorgorjanc** [comment]
@brettellebi yeah, that can be a challenge on its own! Python has multiple ways of installing packages - see https://packaging.python.org/tutorials/installing-packages, in particular https://packaging.python.org/tutorials/installing-packages/#source-distributions-vs-wheels to install from the source - we want to provide better support for this going forward!

**Comment by gregorgorjanc** [comment]
This will be sorted as part of https://github.com/AlphaGenes/AlphaImpute2/issues/13
