### ISSUE TITLE
How does AlphaImpute2 handle sex chromosomes?

### ISSUE THREAD

**Issue by sgavril** [AlphaGenes/AlphaImpute2#14]
Hi all,

I've been working with AlphaImpute2 more closely now and a question that has come up is how this software handles x chromosomes for males? I couldn't find anything in the bioRxiv paper or in the PDF user manual referring to this. Would the male x chromosome just be treated as diploid and homozygous at every SNP? Apologies if this has been answered elsewhere.

**Comment by gregorgorjanc** [comment]
Hi @sgavril I think Andrew did not consider X chromosome

**Comment by sgavril** [comment]
Great to know, thanks for the quick response @gregorgorjanc
