### ISSUE TITLE
Unclear input file formats

### ISSUE THREAD

**Issue by mmudado** [AlphaGenes/AlphaImpute2#3]
In the AlphaImpute2.pdf file distributed, in the Input File Format section, Genotype File subsection, it is written:

"The remaining values are the genotypes of the individual at each locus, either 0, 1, or 2 (or 9 if missing)."

It is unclear if "0" stands for homozigous genotypes for the first alelle, "1" stands for heterozigous genotypes and "2" stands for homoziguous genotypes for the other alelle. This is usually the case for other softwares, but can be confusing for newbies using your software.

Please clarify this in the documentation.

**Comment by gregorgorjanc** [comment]
Thanks, @mmudado! Yes, 0 is major/ref allele homozygote etc. I think this is fairly certain when dealing with diploid allele dosages.
