### ISSUE TITLE
Binary plink file input error

### ISSUE THREAD

**Issue by sgavril** [AlphaGenes/AlphaImpute2#4]
Hello,

I have binary input files generated by plink (.bed and .bim). I read in the documentation that AlphaImpute2 supports binary plink file input with alphaplinkpython, so I downloaded the most recent version (0.08). When I run AlphaImpute2, I get a file not found error.

First as a sanity check, the files are present:

`(python3.6) [stefan@stefan-81x2 05_AlphaImpute2]$ ls
alphaImpute2.sh  alphaplinkpython-0.0.8-cp36-cp36m-manylinux1_x86_64.whl  testFile.bed  testFile.bim`

The command I executed:

`AlphaImpute2 -bfile testFile -out testOut  -maxthreads 4`

And the output: 
[alphaImpute2output.txt](https://github.com/AlphaGenes/AlphaImpute2/files/6177080/alphaImpute2output.txt)

I am not sure how to go about fixing this. I first tried this with the file extension name in the input and that gave me similar results. Does anyone have any thoughts?

**Comment by gregorgorjanc** [comment]
Hi @sgavril! Did  you install the alphaplinkpython wheel?

**Comment by sgavril** [comment]
Hello @gregorgorjanc, 
Yes, I had to make a conda environment with python 3.6. Here is my current installation:

`
(python3.6) [stefan@stefan-81x2 05_AlphaImpute2]$ pip show alphaplinkpython
Name: alphaplinkpython
Version: 0.0.8
Summary: AlphaGenes library for dealitng with plink
Home-page: UNKNOWN
Author: david
Author-email: david.wilson@roslin.ed.ac.uk
License: GPL
Location: /home/stefan/anaconda3/envs/python3.6/lib/python3.6/site-packages
Requires: cython, numpy
Required-by: 
`

**Comment by gregorgorjanc** [comment]
And you still get the same error as shown above when you have alphaplinkpython installed?

**Comment by sgavril** [comment]
Yes, same output. I am confused because there is a file not found error, but the AlphaImpute2 appears to proceed before erroring out. It seems that the file is found, and that the 'IndexError: tuple index out of range' is the issue?

**Comment by sgavril** [comment]
Hello,

I believe my previous set of input files were corrupted, as I have generated new inputs and everything seems to be running smoothly. My apologies for any confusion.
